### ISSUE TITLE
The deletion of items is not working

### ISSUE THREAD

**Issue by Joltrix** [StarcounterSamples/People#41] opened 2016-08-30 14:02 UTC
When you delete an item, for example a telephone number, or an address, or a person, they get deleted. At least for all intents and purposes. They disappear from the application, and they do not reappear again.

However, all the "items" still exist in the database, they are not deleted in there.

**Comment by warpech** [comment] 2017-01-25 12:14
@threezol could you please check if this is still relevant in the `develop` branch?

**Comment by threezool** [comment] 2017-01-26 15:13
@warpech The relation entry is removed but not the actual data. Tested on both the EmailAddress and PhoneNumber table.

**Comment by warpech** [comment] 2017-01-27 10:57
Thanks for reproducing this. Could you please try to fix this?

**Comment by threezool** [comment] 2017-01-30 13:26
It looks like the issue is in the Delete() function in for example PhoneNumberRelationPage so i'm not sure its related to the people app.

**Comment by Joltrix** [comment] 2017-01-31 10:01
@threezool , It is fixable inside the People app, at least for all the fields except for the custom fields (due to this [issue](https://github.com/StarcounterSamples/People/issues/66) ).

You just need to delete the items from the database as they are being deleted from the viewmodel :)

**Comment by warpech** [comment] 2017-02-06 18:45
@un-tone could you please take it?

**Comment by un-tone** [comment] 2017-02-07 14:22
Created PR https://github.com/StarcounterSamples/People/pull/69

**Comment by un-tone** [comment] 2017-02-09 09:31
Closing as done

**Closed by un-tone** 2017-02-09 09:31 UTC
Labels: bug, P/Medium
